spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/translation_db}
      auto-index-creation: true
  application:
    name: translation-service

jwt:
  secret: ${JWT_SECRET:R0xkc2o0dGJqa3FzbDJoZXN2bGtycXV1dGt2cDExbXQ=}
  expiration-millis: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds

